version: 2

restore_cache: &restore_cache
  restore_cache:
    keys:
      - bundle-d0a0802f-7e10-4e22-931b-4b193231b93c-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
      - bundle-d0a0802f-7e10-4e22-931b-4b193231b93c-{{ .Environment.CIRCLE_JOB }}-

bundle: &bundle
  run: bundle install --path vendor/bundle

save_cache: &save_cache
  save_cache:
    key: bundle-d0a0802f-7e10-4e22-931b-4b193231b93c-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
    paths:
      - vendor/bundle

rspec: &rspec
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *bundle
    - <<: *save_cache
    - run: bundle exec rake spec

rubocop: &rubocop
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *bundle
    - <<: *save_cache
    - run: bundle exec rake internal_investigation

jobs:
  confirm_config_and_documentation:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *bundle
      - <<: *save_cache
      - run: bundle exec rake confirm_config documentation_syntax_check confirm_documentation

  # Ruby 2.1
  ruby-2.1-rspec:
    docker:
      - image: circleci/ruby:2.1
    <<: *rspec
  ruby-2.1-rubocop:
    docker:
      - image: circleci/ruby:2.1
    <<: *rubocop

  # Ruby 2.2
  ruby-2.2-rspec:
    docker:
      - image: circleci/ruby:2.2
    <<: *rspec
  ruby-2.2-rubocop:
    docker:
      - image: circleci/ruby:2.2
    <<: *rubocop

  # Ruby 2.3
  ruby-2.3-rspec:
    docker:
      - image: circleci/ruby:2.3
    <<: *rspec
  ruby-2.3-rubocop:
    docker:
      - image: circleci/ruby:2.3
    <<: *rubocop

  # Ruby 2.4
  ruby-2.4-rspec:
    docker:
      - image: circleci/ruby:2.4
    <<: *rspec
  ruby-2.4-rubocop:
    docker:
      - image: circleci/ruby:2.4
    <<: *rubocop

  # Ruby 2.5
  ruby-2.5-rspec:
    docker:
      - image: circleci/ruby:2.5
    <<: *rspec
  ruby-2.5-rubocop:
    docker:
      - image: circleci/ruby:2.5
    <<: *rubocop

  # JRuby
  jruby:
    docker:
      - image: circleci/jruby:9.1
    steps:
      - checkout
      - run: sudo apt-get install -y make
      - <<: *restore_cache
      - <<: *bundle
      - <<: *save_cache
      - run: bundle exec rake internal_investigation spec

  code-climate:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *bundle
      - <<: *save_cache
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run specs
          command: |
            ./cc-test-reporter before-build
            rake coverage
            ./cc-test-reporter after-build --exit-code $?

workflows:
  version: 2
  build:
    jobs:
      - confirm_config_and_documentation

      # Use `requires: [confirm_config_and_documentation]` to trick Circle CI into starting the slow jruby job early.
      - ruby-2.1-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.1-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.2-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.2-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.3-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.3-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.4-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.4-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.5-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.5-rubocop:
          requires: [confirm_config_and_documentation]
      - jruby
      - code-climate
