version: 2

rspec: &rspec
  environment:
    CODECOV_TOKEN: d40a4678-42fe-4431-bc1a-ccba8363f16b
  steps:
    - checkout
    - run: bundle install
    - run: rake spec

rubocop: &rubocop
  steps:
    - checkout
    - run: bundle install
    - run: rake internal_investigation

jobs:
  confirm_config_and_documentation:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: bundle install
      - run: rake confirm_config documentation_syntax_check confirm_documentation

  # Ruby 2.2
  ruby-2.2-rspec:
    docker:
      - image: circleci/ruby:2.2
    <<: *rspec
  ruby-2.2-rubocop:
    docker:
      - image: circleci/ruby:2.2
    <<: *rubocop

  # Ruby 2.3
  ruby-2.3-rspec:
    docker:
      - image: circleci/ruby:2.3
    <<: *rspec
  ruby-2.3-rubocop:
    docker:
      - image: circleci/ruby:2.3
    <<: *rubocop

  # Ruby 2.4
  ruby-2.4-rspec:
    docker:
      - image: circleci/ruby:2.4
    <<: *rspec
  ruby-2.4-rubocop:
    docker:
      - image: circleci/ruby:2.4
    <<: *rubocop

  # Ruby 2.5
  ruby-2.5-rspec:
    docker:
      - image: circleci/ruby:2.5
    <<: *rspec
  ruby-2.5-rubocop:
    docker:
      - image: circleci/ruby:2.5
    <<: *rubocop

  # JRuby
  jruby:
    docker:
      - image: circleci/jruby:9
    steps:
      - checkout
      - run: sudo apt-get install -y make
      - run: bundle lock
      - restore_cache:
          keys:
            - bundle-v2-{{ checksum "Gemfile.lock" }}
            - bundle-v2-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: rake internal_investigation spec

workflows:
  version: 2
  build:
    jobs:
      - confirm_config_and_documentation

      # Use `requires: [confirm_config_and_documentation]` to trick Circle CI into starting the slow jruby job early.
      - ruby-2.2-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.2-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.3-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.3-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.4-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.4-rubocop:
          requires: [confirm_config_and_documentation]
      - ruby-2.5-rspec:
          requires: [confirm_config_and_documentation]
      - ruby-2.5-rubocop:
          requires: [confirm_config_and_documentation]
      - jruby
